version: "3"
services:
  batfish:
    image: "batfish/batfish"
    ports:
      - "9996:9996"
      - "9997:9997"
  netomox-exp:
    build:
      context: ./repos/netomox-exp
      dockerfile: Dockerfile
    environment:
      BATFISH_HOST: batfish
      BATFISH_WRAPPER_HOST: batfish-wrapper:5000
      MDDO_CONFIGS_DIR: ${MDDO_CONFIGS_DIR}
      MDDO_MODELS_DIR: ${MDDO_MODELS_DIR}
      MDDO_NETOVIZ_MODEL_DIR: ${MDDO_NETOVIZ_MODEL_DIR}
    volumes:
      - ./repos/netomox-exp:/netomox-exp # for development
      - ${SHARED_CONFIGS_DIR}:${MDDO_CONFIGS_DIR}
      - ${SHARED_MODELS_DIR}:${MDDO_MODELS_DIR}
      - ${SHARED_NETOVIZ_MODEL_DIR}:${MDDO_NETOVIZ_MODEL_DIR}
    command: bash -c "bundle exec rake"
    depends_on:
      - batfish-wrapper
  netoviz:
    image: netoviz/allinone
    ports:
      - "3000:3000"
    volumes:
      - ${SHARED_NETOVIZ_MODEL_DIR}:/home/netoviz/static/model
  batfish-wrapper:
    build:
      context: ./repos/batfish-wrapper
      dockerfile: Dockerfile
    environment:
      BATFISH_HOST: batfish
    ports:
      - "5000:5000"
    volumes:
      - ./repos/batfish-wrapper:/batfish-wrapper # for development
      - ${SHARED_CONFIGS_DIR}:${MDDO_CONFIGS_DIR}
      - ${SHARED_MODELS_DIR}:${MDDO_MODELS_DIR}
    depends_on:
      - batfish
  proxy:
    image: nginx
    volumes:
      - ./repos/fish-tracer/proxy/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "15000:80"
    depends_on:
      - fish-tracer
      - batfish-wrapper
  fish-tracer:
    build:
      context: ./repos/fish-tracer
      dockerfile: Dockerfile
    environment:
      BASE_URL: ${FISH_TRACER_BASE_URL}
    volumes:
      - ./repos/fish-tracer/components:/fish-tracer/components
      - ./repos/fish-tracer/layouts:/fish-tracer/layouts
      - ./repos/fish-tracer/nuxt.config.js:/fish-tracer/nuxt.config.js
      - ./repos/fish-tracer/pages:/fish-tracer/pages
      - ./repos/fish-tracer/static:/fish-tracer/static
      - ./repos/fish-tracer/store:/fish-tracer/store
    depends_on:
      - batfish-wrapper
