version: "3"
services:
  batfish:
    image: ${BATFISH_IMAGE}:${BATFISH_IMAGE_TAG}
    ports:
      - 9996:9996
      - 9997:9997
  netomox-exp:
    image: ${NETOMOX_EXP_IMAGE}:${NETOMOX_EXP_IMAGE_TAG}
    tty: true
    environment:
      BATFISH_WRAPPER_HOST: batfish-wrapper:${BATFISH_WRAPPER_PORT}
      NETOMOX_LOG_LEVEL: ${NETOMOX_LOG_LEVEL}
      TOPOLOGY_BUILDER_LOG_LEVEL: ${TOPOLOGY_BUILDER_LOG_LEVEL}
      MDDO_CONFIGS_DIR: ${MDDO_CONFIGS_DIR}
      MDDO_MODELS_DIR: ${MDDO_MODELS_DIR}
      MDDO_NETOVIZ_MODEL_DIR: ${MDDO_NETOVIZ_MODEL_DIR}
      MDDO_MULTI_REGION_EXPR_DIR: ${MDDO_MULTI_REGION_EXPR_DIR}
    volumes:
      - ./repos/netomox-exp/model_defs:/netomox-exp/model_defs # for development
      - ./repos/netomox-exp/exe:/netomox-exp/exe # for development
      - ./repos/netomox-exp/Rakefile:/netomox-exp/Rakefile # for development
      - ./repos/netomox-exp/model_info.json:/netomox-exp/model_info.json # for development
      - ${SHARED_CONFIGS_DIR}:${MDDO_CONFIGS_DIR}
      - ${SHARED_MODELS_DIR}:${MDDO_MODELS_DIR}
      - ${SHARED_NETOVIZ_MODEL_DIR}:${MDDO_NETOVIZ_MODEL_DIR}
      - ${SHARED_MULTI_REGION_EXPR_DIR}:${MDDO_MULTI_REGION_EXPR_DIR} # for multi-region-experiments
    depends_on:
      - batfish-wrapper
  batfish-wrapper:
    image: ${BATFISH_WRAPPER_IMAGE}:${BATFISH_WRAPPER_IMAGE_TAG}
    environment:
      BATFISH_HOST: batfish
      MDDO_CONFIGS_DIR: ${MDDO_CONFIGS_DIR}
      MDDO_MODELS_DIR: ${MDDO_MODELS_DIR}
      PYTHONUNBUFFERED: 1
    ports:
      - ${BATFISH_WRAPPER_PORT}:5000
    volumes:
      - ./repos/batfish-wrapper:/batfish-wrapper # for development
      - ${SHARED_CONFIGS_DIR}:${MDDO_CONFIGS_DIR}
      - ${SHARED_MODELS_DIR}:${MDDO_MODELS_DIR}
    depends_on:
      - batfish
