---
services:
  api-proxy:
    depends_on:
      - namespace-relabeler
      - state-conductor

  grafana:
    image: grafana/grafana-oss:10.0.3
    ports:
      - target: 3000
        published: 23000
    environment:
      GF_LOG_LEVEL: ${GRAFANA_LOG_LEVEL}
    volumes:
      # Grafanaの設定ファイル
      - type: bind
        source: ./assets/visualize/grafana/grafana.ini
        target: /etc/grafana/grafana.ini
      # データソースのprovisioning
      - type: bind
        source: ./assets/visualize/grafana/datasources
        target: /etc/grafana/provisioning/datasources
      # ダッシュボードのprovisioning
      - type: bind
        source: ./assets/visualize/grafana/dashboards
        target: /etc/grafana/provisioning/dashboards
    restart: always
    logging:
      options:
        max-size: 50m
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:v2.46.0
    ports:
      - target: 9090
        published: 9090
    volumes:
      # ./prometheus配下に存在する設定ファイルのマウント
      - type: bind
        source: ./assets/visualize/prometheus/
        target: /etc/prometheus/
    command:
      # コンフィグファイルのパスの指定
      - --config.file=/etc/prometheus/prometheus.yaml
      - --log.level=${PROMETHEUS_LOG_LEVEL}
    restart: always
    logging:
      options:
        max-size: 50m
    depends_on:
      - namespace-relabeler

  namespace-relabeler:
    image: ${NAMESPACE_RELABELER_IMAGE}:${NAMESPACE_RELABELER_IMAGE_TAG}
    environment:
      NAMESPACE_RELABELER_LOG_LEVEL: ${NAMESPACE_RELABELER_LOG_LEVEL}
      NETOMOX_EXP_HOST: netomox-exp:${NETOMOX_EXP_PORT}
      CADVISOR_URL: http://cadvisor:8080/metrics
    volumes:
      # for development
      - type: bind
        source: ./repos/namespace-relabeler/src
        target: /opt/namespace-relabeler
    logging:
      options:
        max-size: 50m
    stop_signal: SIGINT
    depends_on:
      - cadvisor
      - netomox-exp

  state-conductor:
    image: ${STATE_CONDUCTOR_IMAGE}:${STATE_CONDUCTOR_IMAGE_TAG}
    environment:
      STATE_CONDUCTOR_LOG_LEVEL: ${STATE_CONDUCTOR_LOG_LEVEL}
      PROMETHEUS_URL: http://prometheus:9090
    volumes:
      # for development
      - type: bind
        source: ./repos/state-conductor
        target: /state-conductor
    depends_on:
      - prometheus

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.38.6
    ports:
      - target: 8080
        published: 20080
    volumes:
      - type: bind
        source: /
        target: /rootfs
        read_only: true
      - type: bind
        source: /var/run
        target: /var/run
      - type: bind
        source: /sys
        target: /sys
        read_only: true
      - type: bind
        source: /var/lib/docker/
        target: /var/lib/docker
        read_only: true
