version: "3"
services:
  batfish:
    image: ${BATFISH_IMAGE}:${BATFISH_IMAGE_TAG}
  netomox-exp:
    image: ${NETOMOX_EXP_IMAGE}:${NETOMOX_EXP_IMAGE_TAG}
    tty: true # for rerun (requires console input)
    ports:
      - ${NETOMOX_EXP_PORT}:9292
    environment:
      NETOMOX_LOG_LEVEL: ${NETOMOX_LOG_LEVEL}
      TOPOLOGY_BUILDER_LOG_LEVEL: ${TOPOLOGY_BUILDER_LOG_LEVEL}
      MDDO_CONFIGS_DIR: ${MDDO_CONFIGS_DIR}
      MDDO_QUERIES_DIR: ${MDDO_QUERIES_DIR}
      MDDO_TOPOLOGIES_DIR: ${MDDO_TOPOLOGIES_DIR}
    volumes:
      # for development
      - ./repos/netomox-exp/model_defs:/netomox-exp/model_defs
      - ./repos/netomox-exp/exe:/netomox-exp/exe
      - ./repos/netomox-exp/Rakefile:/netomox-exp/Rakefile
      - ./repos/netomox-exp/model_info.json:/netomox-exp/model_info.json
      - ./repos/netomox-exp/app.rb:/netomox-exp/app.rb
      # data dirs
      - ${SHARED_CONFIGS_DIR}:${MDDO_CONFIGS_DIR}
      - ${SHARED_QUERIES_DIR}:${MDDO_QUERIES_DIR}
      - ${SHARED_TOPOLOGIES_DIR}:${MDDO_TOPOLOGIES_DIR}
    depends_on:
      - batfish-wrapper
  batfish-wrapper:
    image: ${BATFISH_WRAPPER_IMAGE}:${BATFISH_WRAPPER_IMAGE_TAG}
    environment:
      BATFISH_HOST: batfish
      MDDO_CONFIGS_DIR: ${MDDO_CONFIGS_DIR}
      MDDO_QUERIES_DIR: ${MDDO_QUERIES_DIR}
      PYTHONUNBUFFERED: 1
    volumes:
      - ./repos/batfish-wrapper:/batfish-wrapper # for development
      - ${SHARED_CONFIGS_DIR}:${MDDO_CONFIGS_DIR}
      - ${SHARED_QUERIES_DIR}:${MDDO_QUERIES_DIR}
    depends_on:
      - batfish
  api-proxy:
    image: ${API_PROXY_IMAGE}:${API_PROXY_IMAGE_TAG}
    volumes:
      - ./api-proxy.default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${API_PROXY_PORT}:80
    depends_on:
      - batfish-wrapper
      - netomox-exp
