version: "3"
services:
  netoviz:
    image: ${NETOVIZ_IMAGE}:${NETOVIZ_IMAGE_TAG}
    ports:
      - ${NETOVIZ_PORT}:3000
    environment:
      MDDO_TOPOLOGIES_DIR: /netoviz/static/model
    volumes:
      - ${SHARED_TOPOLOGIES_DIR}:/netoviz/static/model
      - ./repos/netoviz/components:/netoviz/components
      - ./repos/netoviz/layouts:/netoviz/layouts
      - ./repos/netoviz/nuxt.config.js:/netoviz/nuxt.config.js
      - ./repos/netoviz/lib:/netoviz/lib
      - ./repos/netoviz/pages:/netoviz/pages
      - ./repos/netoviz/server:/netoviz/server
      - ./repos/netoviz/static:/netoviz/static
      - ./repos/netoviz/store:/netoviz/store
  fish-tracer:
    image: ${FISH_TRACER_IMAGE}:${FISH_TRACER_IMAGE_TAG}
    environment:
      BASE_URL: http://${FISH_TRACER_BASE_HOST}:${API_PROXY_PORT}
    volumes:
      - ./repos/fish-tracer/components:/fish-tracer/components
      - ./repos/fish-tracer/layouts:/fish-tracer/layouts
      - ./repos/fish-tracer/nuxt.config.js:/fish-tracer/nuxt.config.js
      - ./repos/fish-tracer/pages:/fish-tracer/pages
      - ./repos/fish-tracer/static:/fish-tracer/static
      - ./repos/fish-tracer/store:/fish-tracer/store
    depends_on:
      - batfish-wrapper
