---
- hosts: localhost
  gather_facts: false
  become: yes
  vars:
    mddo_model_file: "./pushed_configs_mddo_network.json"
    links: {}
    nodes: {}
    cnf_image:
      kind: 'crpd'
      image: 'crpd:22.1R1.10'
  tasks:
    - name: 
      set_fact: 
        topology: "{{lookup('file', mddo_model_file) }}"
        
    - name: 
      set_fact:
        topology2: "{{ topology['ietf-network:networks'] | community.general.json_query(query1) }}"
      vars:
        query1: 'network[-1]'

    - name:
      set_fact:
        inout_info: "{{topology2['ietf-network-topology:link']  | community.general.json_query(query1)}}"
      vars:
        query1: '[*].{"dest-node": destination."dest-node", "dest-if": destination."dest-tp", "source-node": source."source-node", "source-if": source."source-tp"}'

    - name: 
      set_fact:
        tmp_uniq_list: "{{ tmp_uniq_list |default([]) + [ { key1: 1, key2: 1 } ]  }}"
      vars:
        key1: "{{ item['dest-node'] }}:{{ item['dest-if'] }}"
        key2: "{{ item['source-node'] }}:{{ item['source-if'] }}"
      loop: "{{ inout_info }}"

    - name:
      set_fact:
        uniq_list: "{{ tmp_uniq_list | unique }}"

    - set_fact:
        links: |-
            [
            {%- for dicts in uniq_list  %}
            {%- set tmplist = dicts.keys() -%}
            {"endpoints":  {{ tmplist }}  },
            {%- endfor %}
            ]

    - set_fact:
        nodes: "{{ nodes | combine( { item['dest-node']: cnf_image } ) }}"
      loop: "{{ inout_info }}"

    - set_fact:
        containerlab:
          name: "mddo-lab"
          topology:
            nodes: "{{ nodes }}"
            links: "{{ links }}"

    - name:
      copy:
        dest: "./tmp-clab-topo.yml"
        content: "{{ containerlab | to_nice_yaml }}"
   
    - name: ifname change
      shell: bash -c "cat ./tmp-clab-topo.yml | sed -e 's/Ethernet/eth/g' -e 's/ge-0\/0\/0/eth1/g'  -e 's/ge-0\/0\/1/eth2/g' -e 's/ge-0\/0\/2/eth3/g' -e 's/ge-0\/0\/3/eth4/g' -e 's/ge-0\/0\/4/eth5/g' -e 's/ge-0\/0\/5/eth6/g'  -e 's/ge-0\/0\/6/eth7/g'  -e 's/ge-0\/0\/7/eth8/g' -e 's/enp1s4/eth1/g' -e 's/enp1s5/eth2/g' > ./clab-topo.yml"
