---
- name: upload config
  uri:
    url: "{{ url }}"
    method: POST
    return_content: false
    body_format: json
    headers:
      Content-Type: "application/json"
    body: [{"filename": "{{ filepath | basename }}", "text": "{{ lookup('file', \"{{ filepath }}\") }}"}]
