---
expected_traffic:
  original_targets:
    - node: edge-tk01
      interface: ge-0/0/3.0
      expected_max_bandwidth: 0.8e9 # bps (e9=Gbps)
  emulated_traffic:
    scale: 1e-2 # 1Gbps to 10Mbps
source_as:
  asn: 65550
  allowed_peers:
    - 172.16.0.5
    - 172.16.1.9
  preferred_peer:
    node: edge-tk01
    interface: ge-0/0/3.0
dest_as:
  asn: 65520
  allowed_peers:
    - 192.168.0.10
    - 192.168.0.14
    - 192.168.0.18
