---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - name: "get convert table"
    uri:
      url: "http://api-proxy/topologies/{{ network_name }}/{{ snapshot_name }}/topology/layer3/config_params"
      method: "GET"
      body_format: json
    register: layer3_convert_table

  - name: generate config
    template:
      src: template/crpd.j2
      dest: "configs/{{ item.name }}.conf"
    when: '"segment" not in item.type'
    loop: "{{ layer3_convert_table.json }}"

  - name: "get ospf node table (select ospf_proc node)"
    uri:
      url: "http://api-proxy/topologies/{{ network_name }}/{{ snapshot_name }}/topology/layer_type_ospf/interfaces?node_type=ospf_proc"
      method: "GET"
      body_format: json
    register: ospf_nodes

  - name: "get layer3 node table (reject segment node)"
    uri:
      url: "http://api-proxy/topologies/{{ network_name }}/{{ snapshot_name }}/topology/layer3/nodes?exc_node_type=segment"
      method: "GET"
      body_format: json
    register: layer3_nodes

  - name: "get bgp_proc node table"
    uri:
      url: "http://api-proxy/topologies/{{ network_name }}/{{ snapshot_name }}/topology/bgp_proc/interfaces"
      method: "GET"
      body_format: json
    register: bgp_proc_nodes

  ## layer3 (static-route) ##
  ## crpd_routingoption_asn.j2       crpd_routingoption_routerid.j2  crpd_routingoption_static.j2
  - name: generate static-route config
    template:
      src: template/crpd_routing-option-static.j2
      dest: "configs/{{ item.node }}_routing-options-static.conf"
    loop: "{{ layer3_nodes.json | json_query('nodes[*]') }}"

  - name: merge static-route config
    shell: "cat configs/{{ item.node }}_routing-options-static.conf >>  configs/{{ item.node }}.conf ; rm configs/{{ item.node }}_routing-options-static.conf"
    loop: "{{ layer3_nodes.json | json_query('nodes[*]') }}"

  - name: generate router-id config
    template:
      src: template/crpd_routing-option-routerid.j2
      dest: "configs/{{ item.node }}_routing-options-routerid.conf"
    loop: "{{ layer3_nodes.json | json_query('nodes[*]') }}"

  - name: merge router-id config
    shell: "cat configs/{{ item.node }}_routing-options-routerid.conf >>  configs/{{ item.node }}.conf ; rm configs/{{ item.node }}_routing-options-routerid.conf"
    loop: "{{ layer3_nodes.json | json_query('nodes[*]') }}"

  - name: generate asn config
    template:
      src: template/crpd_routing-option-asn.j2
      dest: "configs/{{ item.node }}_routing-options-asn.conf"
    loop: "{{ layer3_nodes.json | json_query('nodes[*]') }}"

  - name: merge asn config
    shell: "cat configs/{{ item.node }}_routing-options-asn.conf >>  configs/{{ item.node }}.conf ; rm configs/{{ item.node }}_routing-options-asn.conf"
    loop: "{{ layer3_nodes.json | json_query('nodes[*]') }}"

  ## bgp_proc, bgp policy and peer ##

  - name: generate policy config
    template:
      src: template/crpd_policy.j2
      dest: "configs/{{ item['supports'][0]['node-ref'] }}_policy.conf"
    loop: "{{ bgp_proc_nodes.json | json_query('nodes[*]') }}"

  - name: merge policy config
    shell: "cat configs/{{ item['supports'][0]['node-ref'] }}_policy.conf >> configs/{{ item['supports'][0]['node-ref'] }}.conf ; rm configs/{{ item['supports'][0]['node-ref'] }}_policy.conf"
    loop: "{{ bgp_proc_nodes.json | json_query('nodes[*]') }}"

  - name: generate bgp peer config
    template:
      src: template/crpd_bgp.j2
      dest: "configs/{{ item['supports'][0]['node-ref'] }}_bgp.conf"
    loop: "{{ bgp_proc_nodes.json | json_query('nodes[*]') }}"

  - name: merge bgp peer config
    shell: "cat configs/{{ item['supports'][0]['node-ref'] }}_bgp.conf >> configs/{{ item['supports'][0]['node-ref'] }}.conf ; rm configs/{{ item['supports'][0]['node-ref'] }}_bgp.conf"
    loop: "{{ bgp_proc_nodes.json | json_query('nodes[*]') }}"

  ## ospf ##

  - name: generate ospf config
    template:
      src: template/crpd_ospf.j2
      dest: "configs/{{ item.1.node }}_ospf_area{{item.0.attribute.identifier}}.conf"
    loop: "{{ ospf_nodes.json | subelements('nodes', skip_missing=True) }}"

  - name: merge ospf config
    shell: "cat configs/{{ item.1.node }}_ospf_area{{item.0.attribute.identifier}}.conf >> configs/{{ item.1.node }}.conf ; rm configs/{{ item.1.node }}_ospf_area{{item.0.attribute.identifier}}.conf"
    loop: "{{ ospf_nodes.json | subelements('nodes', skip_missing=True) }}"

  ## bridge ##

  - name: generate bridge data
    set_fact:
      bridge_data: "{{ bridge_data | default([])  + [ data ] }}"
    vars:
      data:
        name: "{{ item.agent_name }}"
        if_list: >-
          {%- for dict in item.if_list -%}
          {%-  if 'description' in dict -%}
          { 'name': '{{ dict.agent_name }}', 'description': '{{ dict.description }}'},
          {%- else -%}
          { 'name': '{{ dict.agent_name }}' },
          {%- endif -%}
          {%- endfor -%}
    when: '"segment" in item.type'
    loop: "{{ layer3_convert_table.json }}"

  - name: generate bridge config
    template:
      src: template/ceos.j2
      dest: "configs/{{ item.name }}.conf"
    loop: "{{ bridge_data }}"

  - name: upload generated config
    include_role:
      name: upload_config
    vars:
      url: "http://api-proxy/configs/{{ network_name }}/{{ snapshot_name }}/"
      filepath: "configs/{{ item.agent_name }}.conf"
    loop: "{{ layer3_convert_table.json }}"

- hosts: docker-host
  gather_facts: false
  become: true
  vars:
    ansible_user: "{{ login_user}}"
    ansible_python_interpreter: /usr/bin/python3
    with_clab: "{{ with_clab }}"

  tasks:
    - name: "get convert table"
      uri:
        url: "http://localhost:15000/topologies/{{ network_name }}/{{ snapshot_name }}/topology/layer3/config_params"
        method: "GET"
        body_format: json
      register: layer3_convert_table

    - copy:
        src: "configs/{{ item.agent_name }}.conf"
        dest: "{{ ansible_runner_dir }}/clab/{{ item.agent_name }}.conf"
      loop: "{{ layer3_convert_table.json }}"
      ignore_errors: true

    - name: "get clab topo yaml"
      uri:
        url: "http://localhost:15000/topologies/{{ network_name }}/{{ snapshot_name }}/topology/layer3/containerlab_topology?image={{ crpd_image }}&bind_license=license.key:/tmp/license.key:ro"
        method: "GET"
        body_format: json
      register: containerlab

    - name: Creating clab-topo.yaml
      copy:
        dest: "{{ ansible_runner_dir }}/clab/clab-topo.yaml"
        content: "{{ containerlab.json | to_yaml }}"

    - name: "delete ovs-br {{ item.key }}"
      shell: "ovs-vsctl del-br {{ item.key }}"
      when: with_clab == "true" and "ovs" in item.value.kind
      loop: "{{ lookup( 'ansible.builtin.dict', containerlab.json.topology.nodes) }}"
      ignore_errors: true

    - name: "create ovs-br {{ item.key }}"
      shell: "ovs-vsctl add-br {{ item.key }}"
      when: with_clab == "true" and "ovs" in item.value.kind
      loop: "{{ lookup( 'ansible.builtin.dict', containerlab.json.topology.nodes) }}"
      ignore_errors: true

    - name: deploy containerlab
      shell:
        cmd: "containerlab deploy --topo clab-topo.yaml --reconfigure"
      args:
        chdir: "{{ ansible_runner_dir }}/clab"
      when: with_clab == "true"
