---
- hosts: docker-host
  gather_facts: false
  become: true
  vars:
    ansible_user: "{{ login_user }}"
    ansible_python_interpreter: /usr/bin/python3
    gen_iperf_command: project/playbooks/{{ usecase_common_name }}/generate_iperf_command.py
    flow_data: project/playbooks/{{ usecase_name }}/flowdata.csv
    static_route_data: project/playbooks/configs/static-route.yaml
    iperf_params_data_runner: configs/iperf_params.json  # in runner container path (origin: this playbook dir)
    iperf_params_data: project/playbooks/configs/iperf_params.json  # in remote host path
    with_clab: "{{ with_clab }}"
    clab_restart: "{{ clab_restart }}"

  tasks:
    - name: deploy containerlab
      shell:
        cmd: "containerlab deploy --topo clab-topo.yaml --reconfigure"
      args:
        chdir: "{{ ansible_runner_dir }}/clab"
      when:
        with_clab == "true" and clab_restart == "true"

    - name: enable bgp license
      shell:
        cmd: "sudo containerlab exec --topo clab-topo.yaml --label clab-node-kind=juniper_crpd --cmd 'cli request system license add /tmp/license.key'"
      args:
        chdir: "{{ ansible_runner_dir }}/clab"
      when:
        with_clab == "true"

    - name: "get layer3 topology (select endpoint node)"
      uri:
        url: "http://localhost:15000/topologies/{{ network_name }}/{{ snapshot_name }}/topology/layer3/interfaces?node_type=endpoint"
        method: "GET"
        body_format: json
      register: layer3_nodes

    - name: generate iperf endpoint static-route info
      set_fact:
        iperf_list: "{{ iperf_list | default([]) + [ item ] }}"
      loop: "{{ layer3_nodes.json | json_query('nodes[*]') }}"

    - name: setting eth1 & default routing
      shell:
        cmd: "{{ exec_container }} {{ add_eth1_ip }}; {{ exec_container }} {{ del_default_route }}; {{ exec_container }} {{ add_default_route }}"
      args:
        chdir: "{{ ansible_runner_dir }}/clab"
      vars:
        exec_container: "sudo containerlab inspect --all --format json | jq '.containers[] | select( .name | contains (\"{{ item['node-id'] }}\")) | .name' | xargs -ICONTAINER docker exec CONTAINER "
        add_eth1_ip: 'ip addr add {{ item["interfaces"][0]["attribute"]["ip-address"][0] }} dev eth1 '
        del_default_route: "ip route del default via 172.20.20.1"
        add_default_route: 'ip route add default via {{ item["attribute"]["static-route"][0]["next-hop"] }}'
      loop: "{{ iperf_list }}"
      ignore_errors: true
      when:
        with_clab == "true"

    - name: create static-route.yaml (as input for generate_iperf_command.py)
      copy:
        dest: "{{ ansible_runner_dir }}/project/playbooks/configs/static-route.yaml"
        content: "{{ iperf_list | to_yaml }}"

    - name: generate iperf command parameter
      shell:
        cmd: "python3 {{ gen_iperf_command }} -f {{ flow_data }} -s {{ static_route_data }} > {{ iperf_params_data }}"
      args:
        chdir: "{{ ansible_runner_dir }}"

    - name: iperf server command (debug)
      debug:
        msg: '{{ exec_container }} /bin/bash -c "nohup iperf3 -s -p {{ item.1.server_port }} > out_{{ item.1.server_port }}.log &"'
      vars:
        exec_container: "sudo containerlab inspect --all --format json | jq '.containers[] | select( .name | contains (\"{{ item.0['server_node'] }}\")) | .name' | xargs -ICONTAINER docker exec CONTAINER "
      with_subelements:
        - "{{ lookup('file', iperf_params_data_runner) }}"
        - clients

    - name: iperf server command
      shell:
        cmd: '{{ exec_container }} /bin/bash -c "nohup iperf3 -s -p {{ item.1.server_port }} > out_{{ item.1.server_port }}.log 2>&1 &"'
      vars:
        exec_container: "sudo containerlab inspect --all --format json | jq '.containers[] | select( .name | contains (\"{{ item.0['server_node'] }}\")) | .name' | xargs -ICONTAINER docker exec CONTAINER "
      with_subelements:
        - "{{ lookup('file', iperf_params_data_runner) }}"
        - clients
      when:
        with_clab == "true"

    - name: iperf client command (debug)
      debug:
        msg: '{{ exec_container }} /bin/bash -c "nohup iperf3 -t 0 -c {{ item.1["server_address"] }} -b {{ item.1.rate | int }}K -p {{ item.1.server_port }} > out_{{ item.0.server_node }}.log &"'
      vars:
        exec_container: "sudo containerlab inspect --all --format json | jq '.containers[] | select( .name | contains (\"{{ item.1['client_node'] }}\")) | .name' | xargs -ICONTAINER docker exec CONTAINER "
      with_subelements:
        - "{{ lookup('file', iperf_params_data_runner) }}"
        - clients

    - name: iperf client command
      shell:
        cmd: '{{ exec_container }} /bin/bash -c "nohup iperf3 -t 0 -c {{ item.1["server_address"] }} -b {{ item.1.rate | int }}K -p {{ item.1.server_port }} > out_{{ item.0.server_node }}.log 2>&1 &"'
      vars:
        exec_container: "sudo containerlab inspect --all --format json | jq '.containers[] | select( .name | contains (\"{{ item.1['client_node'] }}\")) | .name' | xargs -ICONTAINER docker exec CONTAINER "
      with_subelements:
        - "{{ lookup('file', iperf_params_data_runner) }}"
        - clients
      when:
        with_clab == "true"
