---
- hosts: docker-host
  gather_facts: false
  become: true
  vars:
    ansible_user: "{{ login_user}}"
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: save config from  containerlab
      shell:
        cmd: "containerlab save --topo clab-topo.yaml"
      args:
        chdir: "{{ ansible_runner_dir }}/clab"


    - name: "get convert table"
      uri:
        url: "http://localhost:15000/topologies/{{ network_name }}/emulated_asis/topology/layer3/config_params"
        method: "GET"
        body_format: json
      register: node_list

    - name: copy from crpd config & send ansible-runner /tmp directory
      ansible.builtin.fetch:
        src: "{{ ansible_runner_dir }}/clab/clab-emulated/{{ item.agent_name }}/config/juniper.conf"
        dest: "/tmp/{{ item.agent_name }}.conf"
        flat: true
      when: '"node" == item.type or "endpoint" == item.type'
      loop: "{{ node_list.json }}"

    - name: upload router config
      include_role:
        name: uploadconfig
      vars:
        url: "http://localhost:15000/configs/{{ network_name }}/emulated_tobe/"
        filepath: "/tmp/{{ item.agent_name }}.conf"
      when: '"node" == item.type or "endpoint" == item.type'
      loop: "{{ node_list.json }}"

    - name: upload switch config
      include_role:
        name: uploadconfig
      vars:
        url: "http://localhost:15000/configs/{{ network_name }}/emulated_tobe/"
        filepath: "configs/{{ item.agent_name }}.conf"
      when: '"segment" == item.type'
      loop: "{{ node_list.json }}"
