---
version: 1
 
build_arg_defaults:
  EE_BASE_IMAGE: quay.io/ansible/ansible-runner:stable-2.12-latest
  #EE_BASE_IMAGE: quay.io/ansible/ansible-runner:stable-2.12-devel
 
ansible_config: ansible.cfg
 
dependencies:
  galaxy: requirements.yml
  python: requirements.txt
 
additional_build_steps:
  prepend:
    - RUN whoami
    - RUN cat /etc/os-release
  append:
    - RUN echo This is a post-install command!
    - RUN ls -la /etc

