---
expected_traffic:
  original_targets:
    - node: edge-tk01
      interface: ge-0/0/3.0
      expected_max_bandwidth: 0.8e9 # bps (e9=Gbps)
  emulated_traffic:
    scale: 1e-2 # 1Gbps to 10Mbps
source_ases:
  - asn: 65550
    regions:
      - region: tokyo
        prefixes:
          - 10.0.1.0/24
          - 10.0.2.0/24
        allowed_peers:
          - peer: 172.16.0.5 # edge-tk01
            type: pni
          # - peer: 172.16.1.x # edge-tk02/vlan shared
          #   type: ix
    preferred_peer:
      node: edge-tk01
      interface: ge-0/0/3.0
  - asn: 65560
    regions:
      - region: tokyo
        prefixes:
          - 10.0.3.0/24
          - 10.0.4.0/24
        allowed_peers:
          - peer: 172.16.1.9 # edge-tk02/vlan shared
            type: ix
          # - peer: 172.16.x.x # edge-tk03
          #   type: pni
    preferred_peer:
      node: edge-tk02
      interface: ge-0/0/3.0
dest_as:
  asn: 65520
  allowed_peers:
    - 192.168.0.18 # edge-tk03
