
scrape_configs:
  - job_name: worker_cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
        -  192.168.23.32:30080

  - job_name: node_exporter
    scrape_interval: 10s
    static_configs:
      - targets:
        - 192.168.23.32:9100
      
