---
- name: deploycontainerlab
  hosts: localhost

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 48090

  rules:
    - name: clab deploy
      condition: event.payload.message == "clab"
      action:
        run_playbook:
          name: "{{ event.payload.ansible_runner_dir }}/project/playbooks/containerlab.yaml"
          extra_vars:
            network_name: "{{ event.payload.network_name }}"
            crpd_image: "{{ event.payload.crpd_image }}"
            ansible_runner_dir: "{{ event.payload.ansible_runner_dir }}"
            snapshot_name: "{{ event.payload.snapshot_name }}"
            usecase_name: "{{ event.payload.usecase_name }}"
            with_clab: "true"
            remote_address: "{{ event.payload.remote_address }}"
    - name: setup iperf node
      condition: event.payload.message == "iperf"
      action:
        run_playbook:
          name: "{{ event.payload.ansible_runner_dir }}/project/playbooks/iperf.yaml"
          extra_vars:
            network_name: "{{ event.payload.network_name }}"
            crpd_image: "{{ event.payload.crpd_image }}"
            ansible_runner_dir: "{{ event.payload.ansible_runner_dir }}"
            snapshot_name: "{{ event.payload.snapshot_name }}"
            usecase_name: "{{ event.payload.usecase_name }}"
            with_clab: "true"
            remote_address: "{{ event.payload.remote_address }}"
    - name: clab destory
      condition: event.payload.message == "destroy"
      action:
        run_playbook:
          name: "{{ event.payload.ansible_runner_dir }}/project/playbooks/destroy.yaml"
          extra_vars:
            network_name: "{{ event.payload.network_name }}"
            crpd_image: "{{ event.payload.crpd_image }}"
            ansible_runner_dir: "{{ event.payload.ansible_runner_dir }}"
            snapshot_name: "{{ event.payload.snapshot_name }}"
            usecase_name: "{{ event.payload.usecase_name }}"
            with_clab: "true"
            remote_address: "{{ event.payload.remote_address }}"
