---
- name: Hello Events
  hosts: localhost

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 48080

  rules:
    - name: playground
      condition: event.payload.message == "controller"
      action:
        run_playbook:
          name: /playbooks/controller.yaml
          extra_vars:
            network_name: "{{ event.payload.network_name }}"
            crpd_image: "{{ event.payload.crpd_image }}"
            snapshot_name: "{{ event.payload.snapshot_name }}"
            usecase_name: "{{ event.payload.usecase_name }}"
            worker_port: "{{ event.payload.worker_port }}"
            worker_node_address: "{{ event.payload.worker_node_address }}"
            remote_address: "{{ event.payload.remote_address }}"
