# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

group :production do
  gem 'httpclient', '>= 2.8.3'
  gem 'test-unit', '>= 3.5.3'
  gem 'thor', '~> 1.2.1'
end

group :development do
  gem 'rubocop', '>= 0.80'
end
