- hosts: docker-host
  gather_facts: false
  become: yes
  vars:
    ansible_user: "{{ login_user}}"
    ansible_password: "{{ login_pass }}"
    ansible_sudo_pass: "{{ sudo_pass }}"
    ansible_python_interpreter: /usr/bin/python3
    mddo_containerlab_file: "./clab-topo.yml"
    operation: create
    #operation: delete

  tasks:
     - copy:
        src: "rt1.xml"
        dest: "/tmp/rt1.xml"

     - name: add host values
       add_host:
         groups: "clab"
         name: "rt1"
         ansible_host: "172.20.20.8"
         #ansible_host: "clab-mddo-lab-rt1"
         ansible_network_os: "junos"
         #ansible_user: "vrnetlab"
         ansible_user: "root"
         ansible_password: "VR-netlab9"

- hosts: clab
  gather_facts: false
  vars:
    mddo_model_file: "./pushed_configs_mddo_network.json"
    nodes: {}
    containerlab: []
    convertif: []
    nodered_url: "http://192.168.80.2:1880"
  tasks:
  - name: show config
    junipernetworks.junos.junos_command:
      commands: show configuration
      display: xml

  - name:
    junipernetworks.junos.junos_l3_interfaces:
      running_config: "{{ lookup('file', '/tmp/rt1.xml') }}"
      state: parsed

