---
- hosts: docker-host
  gather_facts: false
  become: yes
  vars:
    ansible_user: "{{ login_user}}"
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: "run remove_clab.sh"
      shell: "sudo bash remove_clab.sh"
      args:
        chdir: "{{ ansible_runner_dir }}/project"
