---
- hosts: docker-host
  gather_facts: false
  become: yes
  vars:
    ansible_user: "{{ login_user}}"
    ansible_python_interpreter: /usr/bin/python3
#    mddo_model_file: "/data/project/playbooks/pushed_configs_mddo_network.json"
#    nodered_url: "http://192.168.80.2:1880"
#    network_name: "mddo-ospf"
#    netoviz_url: "http://localhost:3000"
#    labname: "mddo-lab"
#    containerlab_host: "172.17.0.1"
#    mddo_containerlab_file: "configs/clab-topo.yml"
#    ansible_runner_dir: ""
#    playground_dir: ""
#    model_merge_dir: ""
#    demo_dir: "{{ playground_dir }}/configs/{{ network_name }}"
#    operation: save
#  pre_tasks:
#    - name: Get ansible_user home directory
#      shell: 'getent passwd "{{ansible_ssh_user}}" | cut -d: -f6'
#      register: ansible_home_result
#
#    - name: Set the fact for the other scripts to use
#      set_fact: ansible_home='{{ansible_home_result.stdout}}'

  tasks:
    - name: save config from  containerlab
      shell:
        cmd: "containerlab save --topo clab-topo.yml"
      args:
        chdir: "{{ ansible_runner_dir }}/clab"


    - name: "get convert table"
      uri:
        url: "http://localhost:15000/topologies/mddo-ospf/emulated_asis/topology/layer3/config_params"
        method: "GET"
        body_format: json
      register: node_list

    - name: copy from crpd config & send ansible-runner /tmp directory
      ansible.builtin.fetch:
        #src: "{{ ansible_home }}/clab-emulated/{{ item.agent_name }}/config/juniper.conf"
        src: "{{ ansible_runner_dir }}/clab/clab-emulated/{{ item.agent_name }}/config/juniper.conf"
        dest: "/tmp/{{ item.agent_name }}.conf"
        flat: yes
      when: '"node" == item.type or "endpoint" == item.type'
      loop: "{{ node_list.json }}"

    - name: upload router config
      uri:
        url: http://localhost:15000/configs/mddo-ospf/emulated_tobe/
        method: POST
        return_content: no
        body_format: json
        headers:
          Content-Type: "application/json"
        body: [{"filename": "{{ item.agent_name }}.conf", "text": "{{ lookup('file', \"/tmp/{{ item.agent_name }}.conf\") }}"}]
      when: '"node" == item.type or "endpoint" == item.type'
      loop: "{{ node_list.json }}"


    - name: upload switch config
      uri:
        url: http://localhost:15000/configs/mddo-ospf/emulated_tobe/
        method: POST
        return_content: no
        body_format: json
        headers:
          Content-Type: "application/json"
        body: [{"filename": "{{ item.agent_name }}.conf", "text": "{{ lookup('file', \"configs/{{ item.agent_name }}.conf\") }}"}]
      when: '"segment" == item.type'
      loop: "{{ node_list.json }}"

