---
  - name: Creating clab-topo.yaml
    copy:
      dest: "{{ ansible_runner_dir }}/clab/static-route.yaml"
      content: "{{ iperf_list | to_yaml }}"

  - name: setting eth1 & default routing
    shell:
      cmd: "{{ common }} {{cmd1}}; {{ common }} {{cmd2}}; {{ common }} {{cmd3}} "
    args:
      chdir: "{{ ansible_runner_dir }}/clab"
    vars: 
        common: "sudo containerlab inspect --all --format json | jq '.containers[] |  select( .name | contains (\"{{ item['node-id'] }}\")) | .name' | xargs -ICONTAINER docker exec CONTAINER "
        cmd1: 'ip addr add {{ item["ietf-network-topology:termination-point"][0]["mddo-topology:l3-termination-point-attributes"]["ip-address"][0] }} dev eth1 '
        cmd2: "ip route del default via 172.20.20.1"
        cmd3: 'ip route add default via {{ item["mddo-topology:l3-node-attributes"]["static-route"][0]["next-hop"] }}'
    loop: "{{ iperf_list }}"
    ignore_errors: True

