---
- name: Create static-route.yaml
  copy:
    dest: "{{ ansible_runner_dir }}/project/playbooks/configs/static-route.yaml"
    content: "{{ iperf_list | to_yaml }}"

- name: setting eth1 & default routing
  shell:
    cmd: "{{ exec_container }} {{ add_eth1_ip }}; {{ exec_container }} {{ del_default_route }}; {{ exec_container }} {{ add_default_route }}"
  args:
    chdir: "{{ ansible_runner_dir }}/clab"
  vars:
    exec_container: "sudo containerlab inspect --all --format json | jq '.containers[] | select( .name | contains (\"{{ item['node-id'] }}\")) | .name' | xargs -ICONTAINER docker exec CONTAINER "
    add_eth1_ip: 'ip addr add {{ item["ietf-network-topology:termination-point"][0]["mddo-topology:l3-termination-point-attributes"]["ip-address"][0] }} dev eth1 '
    del_default_route: "ip route del default via 172.20.20.1"
    add_default_route: 'ip route add default via {{ item["mddo-topology:l3-node-attributes"]["static-route"][0]["next-hop"] }}'
  loop: "{{ iperf_list }}"
  ignore_errors: true
