services:
  grafana:
    image: grafana/grafana-oss:10.0.3
    container_name: grafana
    ports:
      - target: 3000
        published: 23000
    volumes:
        # Grafanaの設定ファイル
      - type: bind
        source: ./grafana/grafana.ini
        #source: ./servers/grafana/grafana.ini
        target: /etc/grafana/grafana.ini
        # データソースのprovisioning
      - type: bind
        source: ./grafana/datasources
        #source: ./servers/grafana/datasources
        target: /etc/grafana/provisioning/datasources
        # ダッシュボードのprovisioning
      - type: bind
        source: ./grafana/dashboards
        #source: ./servers/grafana/dashboards
        target: /etc/grafana/provisioning/dashboards
        # データの永続化
#      - type: volume
#        source: grafana-data
#        target: /var/lib/grafana
    restart: always
    logging:
      options:
        max-size: 50m
    networks:
      - playground_default

  prometheus:
    image: prom/prometheus:v2.46.0
    container_name: prometheus
    ports:
      - target: 9090
        published: 9090
    volumes:
        # ./prometheus配下に存在する設定ファイルのマウント
      - type: bind
        source: ./prometheus/
        target: /etc/prometheus/
        # 収集したデータの永続化用volume
#      - type: volume
#        source: prometheus-data
#        target: /prometheus
    command:
        # コンフィグファイルのパスの指定
      - --config.file=/etc/prometheus/prometheus.yaml
    restart: always
    logging:
      options:
        max-size: 50m
    networks:
      - playground_default

  relabeler:
    image: ghcr.io/ool-mddo/namespace-relabeler:v0.1.1
    container_name: relabeler
    ports:
      - target: 5000
        published: 5000
    environment:
      - NS_CONVERT_TABLE_URL=${NS_CONVERT_TABLE_URL}
      - CADVISOR_URL=${CADVISOR_URL}
    logging:
      options:
        max-size: 50m
    stop_signal: SIGINT
    networks:
      - playground_default

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.38.6
    ports:
      - target: 8080
        published: 20080
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - playground_default

volumes:
  prometheus-data:
  grafana-data:

networks:
  playground_default:
    external: true
