#!/usr/bin/bash

# runtime and environment
ANSIBLE_RUNNER_IMAGE="ghcr.io/ool-mddo/mddo-ansible-runner:v3.1.0"
CRPD_IMAGE="crpd:23.4R1.9"
API_PROXY="localhost:15000"
API_BRIDGE="playground_default"

# all steps: demo user & directory
LOCALSERVER_USER=mddo
PLAYGROUND_DIR="/home/${LOCALSERVER_USER}/playground"

# all steps: target network/usecase name
NETWORK_NAME="mddo-bgp"
USECASE_NAME="multi_src_as_te" # one of [pni_addlink, pni_te, multi_region_te, multi_src_as_te] for mddo-bgp network

CONTROLLER_ADDRESS="192.168.23.33"
#WORKER_ADDRESS="192.168.1.13"
WORKER_ADDRESS="192.168.23.34,192.168.23.35"

# constants
ANSIBLE_RUNNER_DIR="${PLAYGROUND_DIR}/demo/candidate_model_ops"
ANSIBLE_PLAYBOOK_DIR="${ANSIBLE_RUNNER_DIR}/project/playbooks"
NETWORK_INDEX="${ANSIBLE_RUNNER_DIR}/network_index/${NETWORK_NAME}.json"
USECASE_CONFIGS_DIR="${ANSIBLE_PLAYBOOK_DIR}/configs"
USECASE_SESSION_DIR="${ANSIBLE_PLAYBOOK_DIR}/session"
