#!/usr/bin/bash

# runtime and environment
ANSIBLE_RUNNER_IMAGE="ghcr.io/ool-mddo/mddo-ansible-runner:v3.1.0"
CRPD_IMAGE="crpd:23.4R1.9"
API_PROXY="localhost:15000"
API_BRIDGE="playground_default"

# all steps: demo user & directory
LOCALSERVER_USER=mddo
PLAYGROUND_DIR="/home/${LOCALSERVER_USER}/playground"

# all steps: target network/usecase name
NETWORK_NAME="mddo-bgp"
USECASE_NAME="multi_src_as_te" # one of [pni_addlink, pni_te, multi_region_te, multi_src_as_te] for mddo-bgp network
CONTROLLER_ADDRESS="192.168.23.233"
#WORKER_ADDRESS="192.168.23.233"
WORKER_ADDRESS="192.168.23.32,192.168.23.233"

# constants
ANSIBLE_RUNNER_DIR="${PLAYGROUND_DIR}/demo/candidate_model_ops"
ANSIBLE_PLAYBOOK_DIR="${ANSIBLE_RUNNER_DIR}/project/playbooks"
NETWORK_INDEX="${ANSIBLE_RUNNER_DIR}/network_index/${NETWORK_NAME}.json"
USECASE_CONFIGS_DIR="${ANSIBLE_PLAYBOOK_DIR}/configs"
USECASE_SESSION_DIR="${ANSIBLE_PLAYBOOK_DIR}/session"

# step1-2, 2-2: check if the network has bgp(_proc) layer
function use_bgp_proc() {
  network_name=$1
  snapshot_name=$2
  curl -s "http://${API_PROXY}/topologies/${network_name}/${snapshot_name}/topology" \
    | jq '."ietf-network:networks".network[] | ."network-types" | keys[0]' \
    | grep -q mddo-topology:bgp-proc-network
  return $?
}
