#!/usr/bin/bash

# runtime
CRPD_IMAGE="crpd:23.4R1.9"
# environment
ANSIBLE_EDA="localhost:48080" # controller EDA
API_PROXY="localhost:15000"
CADVISOR_PORT=30080
NODE_EXPORTER_PORT=9100
PROMETHEUS="localhost:9090"
WORKER_PORT="48090" # worker EDA port
# controller/worker ip address(es)
CONTROLLER_ADDRESS="192.168.23.33"
WORKER_ADDRESS="192.168.23.34" # e.g.) "192.168.0.1,192.168.0.2,..." when using multiple workers

# all steps: target network/usecase name
NETWORK_NAME="mddo-bgp"
USECASE_NAME="multi_src_as_te" # one of [pni_addlink, pni_te, multi_region_te, multi_src_as_te] for mddo-bgp network

# directory and file
LOCALSERVER_USER=mddo
PLAYGROUND_DIR="/home/${LOCALSERVER_USER}/playground"
DEMO_DIR="${PLAYGROUND_DIR}/demo/candidate_model_ops"
NETWORK_INDEX="${DEMO_DIR}/network_index/${NETWORK_NAME}.json"
USECASE_SESSION_DIR="${DEMO_DIR}/playbooks/session"

