scrape_configs:
  - job_name: cadvisor
    # 5秒間隔でcAdvisorからメトリクスを取得する
    scrape_interval: 5s
    static_configs:
    - targets:
      - cadvisor:8080
  - job_name: relabeled_cadvisor
    scrape_interval: 5s
    static_configs:
    - targets:
      - namespace-relabeler:5000
